version: '3.3'

volumes:
  twdu:

services:
  app:
    image: alexfedosienko/timeweb-domain-updater:latest
    working_dir: /app
    restart: always
    environment:
      - TIMEWEB_TOKEN=
    volumes:
      - twdu:/app/data

