version: '3.3'

services:
  app:
    build:
      context: ./
    working_dir: /app
    restart: always
    environment:
      - TIMEWEB_TOKEN=${TIMEWEB_TOKEN}
    volumes:
      - ./app/data:/app/data
