version: '3.3'

services:
  timeweb-domain-updater:
    build:
      context: ./
    working_dir: /app
    container_name: timeweb-domain-updater
    restart: always
    environment:
      - TIMEWEB_TOKEN=
    volumes:
      - ./app/data:/app/data
